set dotenv-load
set default-list

test:
    go test ./...

build:
    go build ./...

example:
    go run ./example

lexgen:
    go tool lexgen  --package gyoka --build-file ./lexgen/gyoka.json ./lexicons/
