// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.document.updateDocument

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// DocumentUpdateDocument_Input is the input argument to a net.nusno.gyoka.document.updateDocument call.
type DocumentUpdateDocument_Input struct {
	// content: Optional inline content for the document.
	Content *string `json:"content" cborgen:"content"`
	// docType: Document type to update.
	DocType string `json:"docType" cborgen:"docType"`
	// url: Optional source URL for the document.
	Url *string `json:"url" cborgen:"url"`
}

// DocumentUpdateDocument_Output is the output of a net.nusno.gyoka.document.updateDocument call.
type DocumentUpdateDocument_Output struct {
	Content *string `json:"content" cborgen:"content"`
	DocType string  `json:"docType" cborgen:"docType"`
	Url     *string `json:"url" cborgen:"url"`
}

// DocumentUpdateDocument calls the XRPC method "net.nusno.gyoka.document.updateDocument".
func DocumentUpdateDocument(ctx context.Context, c lexutil.LexClient, input *DocumentUpdateDocument_Input) (*DocumentUpdateDocument_Output, error) {
	var out DocumentUpdateDocument_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.document.updateDocument", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
