// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.document.getDocument

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// DocumentGetDocument_Output is the output of a net.nusno.gyoka.document.getDocument call.
type DocumentGetDocument_Output struct {
	Content *string `json:"content" cborgen:"content"`
	DocType string  `json:"docType" cborgen:"docType"`
	Url     *string `json:"url" cborgen:"url"`
}

// DocumentGetDocument calls the XRPC method "net.nusno.gyoka.document.getDocument".
//
// docType: Document type to fetch.
func DocumentGetDocument(ctx context.Context, c lexutil.LexClient, docType string) (*DocumentGetDocument_Output, error) {
	var out DocumentGetDocument_Output

	params := map[string]interface{}{}
	params["docType"] = docType
	if err := c.LexDo(ctx, lexutil.Query, "", "net.nusno.gyoka.document.getDocument", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
