// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.defs

package gyoka

import (
	"encoding/json"
	"fmt"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedDefs_FeedView is a "feedView" in the net.nusno.gyoka.feed.defs schema.
//
// A Gyoka feed entry.
type FeedDefs_FeedView struct {
	// isActive: Whether the feed is currently active.
	IsActive bool `json:"isActive" cborgen:"isActive"`
	// langFilter: Whether language filtering is enabled for the feed.
	LangFilter bool `json:"langFilter" cborgen:"langFilter"`
	// uri: AT-URI of the feed generator record.
	Uri string `json:"uri" cborgen:"uri"`
}

// FeedDefs_PostInput is the input argument to a net.nusno.gyoka.feed.defs call.
type FeedDefs_PostInput struct {
	// cid: CID of the post record.
	Cid string `json:"cid" cborgen:"cid"`
	// feedContext: Context passed through to the client and feed generator.
	FeedContext *string `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	// indexedAt: Timestamp used for feed ordering. Defaults to the current time when omitted.
	IndexedAt *string `json:"indexedAt,omitempty" cborgen:"indexedAt,omitempty"`
	// languages: Optional language tags for the post. The wildcard '*' is accepted, and non-wildcard values are normalized to primary language subtags.
	Languages []string `json:"languages,omitempty" cborgen:"languages,omitempty"`
	// reason: Reason for including the post in the feed skeleton.
	Reason *FeedDefs_PostInput_Reason `json:"reason,omitempty" cborgen:"reason,omitempty"`
	// uri: AT-URI of the app.bsky.feed.post record to add.
	Uri string `json:"uri" cborgen:"uri"`
}

// Reason for including the post in the feed skeleton.
type FeedDefs_PostInput_Reason struct {
	FeedDefs_SkeletonReasonRepost *FeedDefs_SkeletonReasonRepost
	FeedDefs_SkeletonReasonPin    *FeedDefs_SkeletonReasonPin
}

func (t *FeedDefs_PostInput_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_SkeletonReasonRepost != nil {
		t.FeedDefs_SkeletonReasonRepost.LexiconTypeID = "net.nusno.gyoka.feed.defs#skeletonReasonRepost"
		return json.Marshal(t.FeedDefs_SkeletonReasonRepost)
	}
	if t.FeedDefs_SkeletonReasonPin != nil {
		t.FeedDefs_SkeletonReasonPin.LexiconTypeID = "net.nusno.gyoka.feed.defs#skeletonReasonPin"
		return json.Marshal(t.FeedDefs_SkeletonReasonPin)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_PostInput_Reason) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "net.nusno.gyoka.feed.defs#skeletonReasonRepost":
		t.FeedDefs_SkeletonReasonRepost = new(FeedDefs_SkeletonReasonRepost)
		return json.Unmarshal(b, t.FeedDefs_SkeletonReasonRepost)
	case "net.nusno.gyoka.feed.defs#skeletonReasonPin":
		t.FeedDefs_SkeletonReasonPin = new(FeedDefs_SkeletonReasonPin)
		return json.Unmarshal(b, t.FeedDefs_SkeletonReasonPin)
	default:
		return fmt.Errorf("closed unions must match a listed schema")
	}
}

// FeedDefs_PostView is a "postView" in the net.nusno.gyoka.feed.defs schema.
type FeedDefs_PostView struct {
	Cid         string                    `json:"cid" cborgen:"cid"`
	FeedContext *string                   `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	IndexedAt   string                    `json:"indexedAt" cborgen:"indexedAt"`
	Languages   []string                  `json:"languages" cborgen:"languages"`
	Reason      *FeedDefs_PostView_Reason `json:"reason,omitempty" cborgen:"reason,omitempty"`
	Uri         string                    `json:"uri" cborgen:"uri"`
}

type FeedDefs_PostView_Reason struct {
	FeedDefs_SkeletonReasonRepost *FeedDefs_SkeletonReasonRepost
	FeedDefs_SkeletonReasonPin    *FeedDefs_SkeletonReasonPin
}

func (t *FeedDefs_PostView_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedDefs_SkeletonReasonRepost != nil {
		t.FeedDefs_SkeletonReasonRepost.LexiconTypeID = "net.nusno.gyoka.feed.defs#skeletonReasonRepost"
		return json.Marshal(t.FeedDefs_SkeletonReasonRepost)
	}
	if t.FeedDefs_SkeletonReasonPin != nil {
		t.FeedDefs_SkeletonReasonPin.LexiconTypeID = "net.nusno.gyoka.feed.defs#skeletonReasonPin"
		return json.Marshal(t.FeedDefs_SkeletonReasonPin)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedDefs_PostView_Reason) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "net.nusno.gyoka.feed.defs#skeletonReasonRepost":
		t.FeedDefs_SkeletonReasonRepost = new(FeedDefs_SkeletonReasonRepost)
		return json.Unmarshal(b, t.FeedDefs_SkeletonReasonRepost)
	case "net.nusno.gyoka.feed.defs#skeletonReasonPin":
		t.FeedDefs_SkeletonReasonPin = new(FeedDefs_SkeletonReasonPin)
		return json.Unmarshal(b, t.FeedDefs_SkeletonReasonPin)
	default:
		return fmt.Errorf("closed unions must match a listed schema")
	}
}

// FeedDefs_SkeletonReasonPin is a "skeletonReasonPin" in the net.nusno.gyoka.feed.defs schema.
type FeedDefs_SkeletonReasonPin struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.defs#skeletonReasonPin"`
}

// FeedDefs_SkeletonReasonRepost is a "skeletonReasonRepost" in the net.nusno.gyoka.feed.defs schema.
type FeedDefs_SkeletonReasonRepost struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.defs#skeletonReasonRepost"`
	// repost: AT-URI of the app.bsky.feed.repost record associated with this reason.
	Repost string `json:"repost" cborgen:"repost"`
}
