// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.removePost

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedRemovePost_Input is the input argument to a net.nusno.gyoka.feed.removePost call.
type FeedRemovePost_Input struct {
	Feed string                  `json:"feed" cborgen:"feed"`
	Post *FeedRemovePost_PostRef `json:"post" cborgen:"post"`
}

// FeedRemovePost_Output is the output of a net.nusno.gyoka.feed.removePost call.
type FeedRemovePost_Output struct {
	Feed    string                     `json:"feed" cborgen:"feed"`
	Message string                     `json:"message" cborgen:"message"`
	Post    *FeedRemovePost_PostResult `json:"post" cborgen:"post"`
}

// FeedRemovePost_PostRef is a "postRef" in the net.nusno.gyoka.feed.removePost schema.
type FeedRemovePost_PostRef struct {
	// indexedAt: If provided, only the matching post instance at this timestamp is removed.
	IndexedAt *string `json:"indexedAt,omitempty" cborgen:"indexedAt,omitempty"`
	// uri: AT-URI of the app.bsky.feed.post record to remove.
	Uri string `json:"uri" cborgen:"uri"`
}

// FeedRemovePost_PostResult is a "postResult" in the net.nusno.gyoka.feed.removePost schema.
type FeedRemovePost_PostResult struct {
	IndexedAt string `json:"indexedAt" cborgen:"indexedAt"`
	Uri       string `json:"uri" cborgen:"uri"`
}

// FeedRemovePost calls the XRPC method "net.nusno.gyoka.feed.removePost".
func FeedRemovePost(ctx context.Context, c lexutil.LexClient, input *FeedRemovePost_Input) (*FeedRemovePost_Output, error) {
	var out FeedRemovePost_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.removePost", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
