// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.removePostByAuthor

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedRemovePostByAuthor_Input is the input argument to a net.nusno.gyoka.feed.removePostByAuthor call.
type FeedRemovePostByAuthor_Input struct {
	// author: DID of the post author whose posts should be removed.
	Author string `json:"author" cborgen:"author"`
	Feed   string `json:"feed" cborgen:"feed"`
}

// FeedRemovePostByAuthor_Output is the output of a net.nusno.gyoka.feed.removePostByAuthor call.
type FeedRemovePostByAuthor_Output struct {
	Author       string `json:"author" cborgen:"author"`
	DeletedCount int64  `json:"deletedCount" cborgen:"deletedCount"`
	Feed         string `json:"feed" cborgen:"feed"`
	Message      string `json:"message" cborgen:"message"`
}

// FeedRemovePostByAuthor calls the XRPC method "net.nusno.gyoka.feed.removePostByAuthor".
func FeedRemovePostByAuthor(ctx context.Context, c lexutil.LexClient, input *FeedRemovePostByAuthor_Input) (*FeedRemovePostByAuthor_Output, error) {
	var out FeedRemovePostByAuthor_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.removePostByAuthor", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
