// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.batchAddPosts

package gyoka

import (
	"context"
	"encoding/json"
	"fmt"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedBatchAddPosts_EntryInput is the input argument to a net.nusno.gyoka.feed.batchAddPosts call.
type FeedBatchAddPosts_EntryInput struct {
	Feed  string                         `json:"feed" cborgen:"feed"`
	Posts []*FeedBatchAddPosts_PostInput `json:"posts" cborgen:"posts"`
}

// FeedBatchAddPosts_EntryResult is a "entryResult" in the net.nusno.gyoka.feed.batchAddPosts schema.
type FeedBatchAddPosts_EntryResult struct {
	Feed    string                          `json:"feed" cborgen:"feed"`
	Results []*FeedBatchAddPosts_PostResult `json:"results" cborgen:"results"`
}

// FeedBatchAddPosts_Input is the input argument to a net.nusno.gyoka.feed.batchAddPosts call.
type FeedBatchAddPosts_Input struct {
	Entries []*FeedBatchAddPosts_EntryInput `json:"entries" cborgen:"entries"`
}

// FeedBatchAddPosts_Output is the output of a net.nusno.gyoka.feed.batchAddPosts call.
type FeedBatchAddPosts_Output struct {
	Results []*FeedBatchAddPosts_EntryResult `json:"results" cborgen:"results"`
}

// FeedBatchAddPosts_PostInput is the input argument to a net.nusno.gyoka.feed.batchAddPosts call.
type FeedBatchAddPosts_PostInput struct {
	Cid         string                              `json:"cid" cborgen:"cid"`
	FeedContext *string                             `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	IndexedAt   *string                             `json:"indexedAt,omitempty" cborgen:"indexedAt,omitempty"`
	Languages   []string                            `json:"languages,omitempty" cborgen:"languages,omitempty"`
	Reason      *FeedBatchAddPosts_PostInput_Reason `json:"reason,omitempty" cborgen:"reason,omitempty"`
	// uri: AT-URI of the app.bsky.feed.post record to add.
	Uri string `json:"uri" cborgen:"uri"`
}

type FeedBatchAddPosts_PostInput_Reason struct {
	FeedBatchAddPosts_SkeletonReasonRepost *FeedBatchAddPosts_SkeletonReasonRepost
	FeedBatchAddPosts_SkeletonReasonPin    *FeedBatchAddPosts_SkeletonReasonPin
}

func (t *FeedBatchAddPosts_PostInput_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedBatchAddPosts_SkeletonReasonRepost != nil {
		t.FeedBatchAddPosts_SkeletonReasonRepost.LexiconTypeID = "net.nusno.gyoka.feed.batchAddPosts#skeletonReasonRepost"
		return json.Marshal(t.FeedBatchAddPosts_SkeletonReasonRepost)
	}
	if t.FeedBatchAddPosts_SkeletonReasonPin != nil {
		t.FeedBatchAddPosts_SkeletonReasonPin.LexiconTypeID = "net.nusno.gyoka.feed.batchAddPosts#skeletonReasonPin"
		return json.Marshal(t.FeedBatchAddPosts_SkeletonReasonPin)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedBatchAddPosts_PostInput_Reason) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "net.nusno.gyoka.feed.batchAddPosts#skeletonReasonRepost":
		t.FeedBatchAddPosts_SkeletonReasonRepost = new(FeedBatchAddPosts_SkeletonReasonRepost)
		return json.Unmarshal(b, t.FeedBatchAddPosts_SkeletonReasonRepost)
	case "net.nusno.gyoka.feed.batchAddPosts#skeletonReasonPin":
		t.FeedBatchAddPosts_SkeletonReasonPin = new(FeedBatchAddPosts_SkeletonReasonPin)
		return json.Unmarshal(b, t.FeedBatchAddPosts_SkeletonReasonPin)
	default:
		return fmt.Errorf("closed unions must match a listed schema")
	}
}

// FeedBatchAddPosts_PostResult is a "postResult" in the net.nusno.gyoka.feed.batchAddPosts schema.
type FeedBatchAddPosts_PostResult struct {
	Error  *string `json:"error,omitempty" cborgen:"error,omitempty"`
	Status string  `json:"status" cborgen:"status"`
	Uri    string  `json:"uri" cborgen:"uri"`
}

// FeedBatchAddPosts_SkeletonReasonPin is a "skeletonReasonPin" in the net.nusno.gyoka.feed.batchAddPosts schema.
type FeedBatchAddPosts_SkeletonReasonPin struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.batchAddPosts#skeletonReasonPin"`
}

// FeedBatchAddPosts_SkeletonReasonRepost is a "skeletonReasonRepost" in the net.nusno.gyoka.feed.batchAddPosts schema.
type FeedBatchAddPosts_SkeletonReasonRepost struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.batchAddPosts#skeletonReasonRepost"`
	Repost        string `json:"repost" cborgen:"repost"`
}

// FeedBatchAddPosts calls the XRPC method "net.nusno.gyoka.feed.batchAddPosts".
func FeedBatchAddPosts(ctx context.Context, c lexutil.LexClient, input *FeedBatchAddPosts_Input) (*FeedBatchAddPosts_Output, error) {
	var out FeedBatchAddPosts_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.batchAddPosts", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
