// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.unregisterFeed

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedUnregisterFeed_Input is the input argument to a net.nusno.gyoka.feed.unregisterFeed call.
type FeedUnregisterFeed_Input struct {
	// uri: AT-URI of the feed generator record to unregister.
	Uri string `json:"uri" cborgen:"uri"`
}

// FeedUnregisterFeed_Output is the output of a net.nusno.gyoka.feed.unregisterFeed call.
type FeedUnregisterFeed_Output struct {
	Message string `json:"message" cborgen:"message"`
}

// FeedUnregisterFeed calls the XRPC method "net.nusno.gyoka.feed.unregisterFeed".
func FeedUnregisterFeed(ctx context.Context, c lexutil.LexClient, input *FeedUnregisterFeed_Input) (*FeedUnregisterFeed_Output, error) {
	var out FeedUnregisterFeed_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.unregisterFeed", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
