// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.updateFeed

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedUpdateFeed_FeedView is a "feedView" in the net.nusno.gyoka.feed.updateFeed schema.
type FeedUpdateFeed_FeedView struct {
	IsActive   bool   `json:"isActive" cborgen:"isActive"`
	LangFilter bool   `json:"langFilter" cborgen:"langFilter"`
	Uri        string `json:"uri" cborgen:"uri"`
}

// FeedUpdateFeed_Input is the input argument to a net.nusno.gyoka.feed.updateFeed call.
type FeedUpdateFeed_Input struct {
	// isActive: Whether the feed is active.
	IsActive *bool `json:"isActive,omitempty" cborgen:"isActive,omitempty"`
	// langFilter: Whether language filtering is enabled for the feed.
	LangFilter *bool `json:"langFilter,omitempty" cborgen:"langFilter,omitempty"`
	// uri: AT-URI of the feed generator record to update.
	Uri string `json:"uri" cborgen:"uri"`
}

// FeedUpdateFeed_Output is the output of a net.nusno.gyoka.feed.updateFeed call.
type FeedUpdateFeed_Output struct {
	Feed    *FeedUpdateFeed_FeedView `json:"feed" cborgen:"feed"`
	Message string                   `json:"message" cborgen:"message"`
}

// FeedUpdateFeed calls the XRPC method "net.nusno.gyoka.feed.updateFeed".
func FeedUpdateFeed(ctx context.Context, c lexutil.LexClient, input *FeedUpdateFeed_Input) (*FeedUpdateFeed_Output, error) {
	var out FeedUpdateFeed_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.updateFeed", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
