// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.addPost

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedAddPost_Input is the input argument to a net.nusno.gyoka.feed.addPost call.
type FeedAddPost_Input struct {
	// feed: AT-URI of the feed generator record receiving the post.
	Feed string              `json:"feed" cborgen:"feed"`
	Post *FeedDefs_PostInput `json:"post" cborgen:"post"`
}

// FeedAddPost_Output is the output of a net.nusno.gyoka.feed.addPost call.
type FeedAddPost_Output struct {
	Feed    string             `json:"feed" cborgen:"feed"`
	Message string             `json:"message" cborgen:"message"`
	Post    *FeedDefs_PostView `json:"post" cborgen:"post"`
}

// FeedAddPost calls the XRPC method "net.nusno.gyoka.feed.addPost".
func FeedAddPost(ctx context.Context, c lexutil.LexClient, input *FeedAddPost_Input) (*FeedAddPost_Output, error) {
	var out FeedAddPost_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.addPost", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
