// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.batchRemovePosts

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedBatchRemovePosts_EntryInput is the input argument to a net.nusno.gyoka.feed.batchRemovePosts call.
type FeedBatchRemovePosts_EntryInput struct {
	Feed  string                            `json:"feed" cborgen:"feed"`
	Posts []*FeedBatchRemovePosts_PostInput `json:"posts" cborgen:"posts"`
}

// FeedBatchRemovePosts_EntryResult is a "entryResult" in the net.nusno.gyoka.feed.batchRemovePosts schema.
type FeedBatchRemovePosts_EntryResult struct {
	Feed    string                             `json:"feed" cborgen:"feed"`
	Results []*FeedBatchRemovePosts_PostResult `json:"results" cborgen:"results"`
}

// FeedBatchRemovePosts_Input is the input argument to a net.nusno.gyoka.feed.batchRemovePosts call.
type FeedBatchRemovePosts_Input struct {
	Entries []*FeedBatchRemovePosts_EntryInput `json:"entries" cborgen:"entries"`
}

// FeedBatchRemovePosts_Output is the output of a net.nusno.gyoka.feed.batchRemovePosts call.
type FeedBatchRemovePosts_Output struct {
	Results []*FeedBatchRemovePosts_EntryResult `json:"results" cborgen:"results"`
}

// FeedBatchRemovePosts_PostInput is the input argument to a net.nusno.gyoka.feed.batchRemovePosts call.
type FeedBatchRemovePosts_PostInput struct {
	// indexedAt: If provided, only the matching post instance at this timestamp is removed.
	IndexedAt *string `json:"indexedAt,omitempty" cborgen:"indexedAt,omitempty"`
	// uri: AT-URI of the app.bsky.feed.post record to remove.
	Uri string `json:"uri" cborgen:"uri"`
}

// FeedBatchRemovePosts_PostResult is a "postResult" in the net.nusno.gyoka.feed.batchRemovePosts schema.
type FeedBatchRemovePosts_PostResult struct {
	Error  *string `json:"error,omitempty" cborgen:"error,omitempty"`
	Status string  `json:"status" cborgen:"status"`
	Uri    string  `json:"uri" cborgen:"uri"`
}

// FeedBatchRemovePosts calls the XRPC method "net.nusno.gyoka.feed.batchRemovePosts".
func FeedBatchRemovePosts(ctx context.Context, c lexutil.LexClient, input *FeedBatchRemovePosts_Input) (*FeedBatchRemovePosts_Output, error) {
	var out FeedBatchRemovePosts_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.batchRemovePosts", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
