// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.trimFeed

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedTrimFeed_Input is the input argument to a net.nusno.gyoka.feed.trimFeed call.
type FeedTrimFeed_Input struct {
	Feed string `json:"feed" cborgen:"feed"`
	// remain: Number of posts to keep in the feed after trimming.
	Remain int64 `json:"remain" cborgen:"remain"`
}

// FeedTrimFeed_Output is the output of a net.nusno.gyoka.feed.trimFeed call.
type FeedTrimFeed_Output struct {
	DeletedCount int64  `json:"deletedCount" cborgen:"deletedCount"`
	Feed         string `json:"feed" cborgen:"feed"`
	Message      string `json:"message" cborgen:"message"`
}

// FeedTrimFeed calls the XRPC method "net.nusno.gyoka.feed.trimFeed".
func FeedTrimFeed(ctx context.Context, c lexutil.LexClient, input *FeedTrimFeed_Input) (*FeedTrimFeed_Output, error) {
	var out FeedTrimFeed_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.trimFeed", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
