// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.listFeeds

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedListFeeds_Output is the output of a net.nusno.gyoka.feed.listFeeds call.
type FeedListFeeds_Output struct {
	Feeds []*FeedDefs_FeedView `json:"feeds" cborgen:"feeds"`
}

// FeedListFeeds calls the XRPC method "net.nusno.gyoka.feed.listFeeds".
func FeedListFeeds(ctx context.Context, c lexutil.LexClient) (*FeedListFeeds_Output, error) {
	var out FeedListFeeds_Output
	if err := c.LexDo(ctx, lexutil.Query, "", "net.nusno.gyoka.feed.listFeeds", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
