// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.registerFeed

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedRegisterFeed_FeedView is a "feedView" in the net.nusno.gyoka.feed.registerFeed schema.
//
// Registered feed entry.
type FeedRegisterFeed_FeedView struct {
	IsActive   bool `json:"isActive" cborgen:"isActive"`
	LangFilter bool `json:"langFilter" cborgen:"langFilter"`
	// uri: AT-URI of the app.bsky.feed.generator record.
	Uri string `json:"uri" cborgen:"uri"`
}

// FeedRegisterFeed_Input is the input argument to a net.nusno.gyoka.feed.registerFeed call.
type FeedRegisterFeed_Input struct {
	// isActive: Whether the feed is active.
	IsActive *bool `json:"isActive,omitempty" cborgen:"isActive,omitempty"`
	// langFilter: Whether language filtering is enabled for this feed.
	LangFilter *bool `json:"langFilter,omitempty" cborgen:"langFilter,omitempty"`
	// uri: AT-URI of the feed generator record to register.
	Uri string `json:"uri" cborgen:"uri"`
}

// FeedRegisterFeed_Output is the output of a net.nusno.gyoka.feed.registerFeed call.
type FeedRegisterFeed_Output struct {
	Feed    *FeedRegisterFeed_FeedView `json:"feed" cborgen:"feed"`
	Message string                     `json:"message" cborgen:"message"`
}

// FeedRegisterFeed calls the XRPC method "net.nusno.gyoka.feed.registerFeed".
func FeedRegisterFeed(ctx context.Context, c lexutil.LexClient, input *FeedRegisterFeed_Input) (*FeedRegisterFeed_Output, error) {
	var out FeedRegisterFeed_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.registerFeed", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
