// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.getPosts

package gyoka

import (
	"context"
	"encoding/json"
	"fmt"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedGetPosts_Output is the output of a net.nusno.gyoka.feed.getPosts call.
type FeedGetPosts_Output struct {
	Cursor *string                  `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Feed   string                   `json:"feed" cborgen:"feed"`
	Posts  []*FeedGetPosts_PostView `json:"posts" cborgen:"posts"`
}

// FeedGetPosts_PostView is a "postView" in the net.nusno.gyoka.feed.getPosts schema.
type FeedGetPosts_PostView struct {
	Cid         string  `json:"cid" cborgen:"cid"`
	FeedContext *string `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	IndexedAt   string  `json:"indexedAt" cborgen:"indexedAt"`
	// langs: Deprecated alias of languages.
	Langs     []string `json:"langs,omitempty" cborgen:"langs,omitempty"`
	Languages []string `json:"languages" cborgen:"languages"`
	// reason: AT Protocol feed skeleton reason for this post.
	Reason *FeedGetPosts_PostView_Reason `json:"reason,omitempty" cborgen:"reason,omitempty"`
	// uri: AT-URI of the app.bsky.feed.post record.
	Uri string `json:"uri" cborgen:"uri"`
}

// AT Protocol feed skeleton reason for this post.
type FeedGetPosts_PostView_Reason struct {
	FeedGetPosts_SkeletonReasonRepost *FeedGetPosts_SkeletonReasonRepost
	FeedGetPosts_SkeletonReasonPin    *FeedGetPosts_SkeletonReasonPin
}

func (t *FeedGetPosts_PostView_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedGetPosts_SkeletonReasonRepost != nil {
		t.FeedGetPosts_SkeletonReasonRepost.LexiconTypeID = "net.nusno.gyoka.feed.getPosts#skeletonReasonRepost"
		return json.Marshal(t.FeedGetPosts_SkeletonReasonRepost)
	}
	if t.FeedGetPosts_SkeletonReasonPin != nil {
		t.FeedGetPosts_SkeletonReasonPin.LexiconTypeID = "net.nusno.gyoka.feed.getPosts#skeletonReasonPin"
		return json.Marshal(t.FeedGetPosts_SkeletonReasonPin)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedGetPosts_PostView_Reason) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "net.nusno.gyoka.feed.getPosts#skeletonReasonRepost":
		t.FeedGetPosts_SkeletonReasonRepost = new(FeedGetPosts_SkeletonReasonRepost)
		return json.Unmarshal(b, t.FeedGetPosts_SkeletonReasonRepost)
	case "net.nusno.gyoka.feed.getPosts#skeletonReasonPin":
		t.FeedGetPosts_SkeletonReasonPin = new(FeedGetPosts_SkeletonReasonPin)
		return json.Unmarshal(b, t.FeedGetPosts_SkeletonReasonPin)
	default:
		return fmt.Errorf("closed unions must match a listed schema")
	}
}

// FeedGetPosts_SkeletonReasonPin is a "skeletonReasonPin" in the net.nusno.gyoka.feed.getPosts schema.
type FeedGetPosts_SkeletonReasonPin struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.getPosts#skeletonReasonPin"`
}

// FeedGetPosts_SkeletonReasonRepost is a "skeletonReasonRepost" in the net.nusno.gyoka.feed.getPosts schema.
type FeedGetPosts_SkeletonReasonRepost struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.getPosts#skeletonReasonRepost"`
	// repost: AT-URI of the app.bsky.feed.repost record associated with this reason.
	Repost string `json:"repost" cborgen:"repost"`
}

// FeedGetPosts calls the XRPC method "net.nusno.gyoka.feed.getPosts".
//
// cursor: Opaque pagination cursor encoded as <epochMs>::<cid>.
// feed: AT-URI of the feed generator record to read.
// limit: Maximum number of posts to return.
func FeedGetPosts(ctx context.Context, c lexutil.LexClient, cursor string, feed string, limit int64) (*FeedGetPosts_Output, error) {
	var out FeedGetPosts_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	params["feed"] = feed
	if limit != 0 {
		params["limit"] = limit
	}
	if err := c.LexDo(ctx, lexutil.Query, "", "net.nusno.gyoka.feed.getPosts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
