// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.batchAddPosts

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedBatchAddPosts_EntryInput is the input argument to a net.nusno.gyoka.feed.batchAddPosts call.
type FeedBatchAddPosts_EntryInput struct {
	Feed  string                `json:"feed" cborgen:"feed"`
	Posts []*FeedDefs_PostInput `json:"posts" cborgen:"posts"`
}

// FeedBatchAddPosts_EntryResult is a "entryResult" in the net.nusno.gyoka.feed.batchAddPosts schema.
type FeedBatchAddPosts_EntryResult struct {
	Feed    string                          `json:"feed" cborgen:"feed"`
	Results []*FeedBatchAddPosts_PostResult `json:"results" cborgen:"results"`
}

// FeedBatchAddPosts_Input is the input argument to a net.nusno.gyoka.feed.batchAddPosts call.
type FeedBatchAddPosts_Input struct {
	Entries []*FeedBatchAddPosts_EntryInput `json:"entries" cborgen:"entries"`
}

// FeedBatchAddPosts_Output is the output of a net.nusno.gyoka.feed.batchAddPosts call.
type FeedBatchAddPosts_Output struct {
	Results []*FeedBatchAddPosts_EntryResult `json:"results" cborgen:"results"`
}

// FeedBatchAddPosts_PostResult is a "postResult" in the net.nusno.gyoka.feed.batchAddPosts schema.
type FeedBatchAddPosts_PostResult struct {
	Error  *string `json:"error,omitempty" cborgen:"error,omitempty"`
	Status string  `json:"status" cborgen:"status"`
	Uri    string  `json:"uri" cborgen:"uri"`
}

// FeedBatchAddPosts calls the XRPC method "net.nusno.gyoka.feed.batchAddPosts".
func FeedBatchAddPosts(ctx context.Context, c lexutil.LexClient, input *FeedBatchAddPosts_Input) (*FeedBatchAddPosts_Output, error) {
	var out FeedBatchAddPosts_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.batchAddPosts", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
