// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.addPost

package gyoka

import (
	"context"
	"encoding/json"
	"fmt"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedAddPost_Input is the input argument to a net.nusno.gyoka.feed.addPost call.
type FeedAddPost_Input struct {
	// feed: AT-URI of the feed generator record receiving the post.
	Feed string                 `json:"feed" cborgen:"feed"`
	Post *FeedAddPost_PostInput `json:"post" cborgen:"post"`
}

// FeedAddPost_Output is the output of a net.nusno.gyoka.feed.addPost call.
type FeedAddPost_Output struct {
	Feed    string                `json:"feed" cborgen:"feed"`
	Message string                `json:"message" cborgen:"message"`
	Post    *FeedAddPost_PostView `json:"post" cborgen:"post"`
}

// FeedAddPost_PostInput is the input argument to a net.nusno.gyoka.feed.addPost call.
type FeedAddPost_PostInput struct {
	// cid: CID of the post record.
	Cid string `json:"cid" cborgen:"cid"`
	// feedContext: Context passed through to the client and feed generator.
	FeedContext *string `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	// indexedAt: Timestamp used for feed ordering. Defaults to the current time when omitted.
	IndexedAt *string `json:"indexedAt,omitempty" cborgen:"indexedAt,omitempty"`
	// languages: Optional language tags for the post. The wildcard '*' is accepted, and non-wildcard values are normalized to primary language subtags.
	Languages []string `json:"languages,omitempty" cborgen:"languages,omitempty"`
	// reason: Reason for including the post in the feed skeleton.
	Reason *FeedAddPost_PostInput_Reason `json:"reason,omitempty" cborgen:"reason,omitempty"`
	// uri: AT-URI of the app.bsky.feed.post record to add.
	Uri string `json:"uri" cborgen:"uri"`
}

// Reason for including the post in the feed skeleton.
type FeedAddPost_PostInput_Reason struct {
	FeedAddPost_SkeletonReasonRepost *FeedAddPost_SkeletonReasonRepost
	FeedAddPost_SkeletonReasonPin    *FeedAddPost_SkeletonReasonPin
}

func (t *FeedAddPost_PostInput_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedAddPost_SkeletonReasonRepost != nil {
		t.FeedAddPost_SkeletonReasonRepost.LexiconTypeID = "net.nusno.gyoka.feed.addPost#skeletonReasonRepost"
		return json.Marshal(t.FeedAddPost_SkeletonReasonRepost)
	}
	if t.FeedAddPost_SkeletonReasonPin != nil {
		t.FeedAddPost_SkeletonReasonPin.LexiconTypeID = "net.nusno.gyoka.feed.addPost#skeletonReasonPin"
		return json.Marshal(t.FeedAddPost_SkeletonReasonPin)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedAddPost_PostInput_Reason) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "net.nusno.gyoka.feed.addPost#skeletonReasonRepost":
		t.FeedAddPost_SkeletonReasonRepost = new(FeedAddPost_SkeletonReasonRepost)
		return json.Unmarshal(b, t.FeedAddPost_SkeletonReasonRepost)
	case "net.nusno.gyoka.feed.addPost#skeletonReasonPin":
		t.FeedAddPost_SkeletonReasonPin = new(FeedAddPost_SkeletonReasonPin)
		return json.Unmarshal(b, t.FeedAddPost_SkeletonReasonPin)
	default:
		return fmt.Errorf("closed unions must match a listed schema")
	}
}

// FeedAddPost_PostView is a "postView" in the net.nusno.gyoka.feed.addPost schema.
type FeedAddPost_PostView struct {
	Cid         string                       `json:"cid" cborgen:"cid"`
	FeedContext *string                      `json:"feedContext,omitempty" cborgen:"feedContext,omitempty"`
	IndexedAt   string                       `json:"indexedAt" cborgen:"indexedAt"`
	Languages   []string                     `json:"languages" cborgen:"languages"`
	Reason      *FeedAddPost_PostView_Reason `json:"reason,omitempty" cborgen:"reason,omitempty"`
	Uri         string                       `json:"uri" cborgen:"uri"`
}

type FeedAddPost_PostView_Reason struct {
	FeedAddPost_SkeletonReasonRepost *FeedAddPost_SkeletonReasonRepost
	FeedAddPost_SkeletonReasonPin    *FeedAddPost_SkeletonReasonPin
}

func (t *FeedAddPost_PostView_Reason) MarshalJSON() ([]byte, error) {
	if t.FeedAddPost_SkeletonReasonRepost != nil {
		t.FeedAddPost_SkeletonReasonRepost.LexiconTypeID = "net.nusno.gyoka.feed.addPost#skeletonReasonRepost"
		return json.Marshal(t.FeedAddPost_SkeletonReasonRepost)
	}
	if t.FeedAddPost_SkeletonReasonPin != nil {
		t.FeedAddPost_SkeletonReasonPin.LexiconTypeID = "net.nusno.gyoka.feed.addPost#skeletonReasonPin"
		return json.Marshal(t.FeedAddPost_SkeletonReasonPin)
	}
	return nil, fmt.Errorf("can not marshal empty union as JSON")
}

func (t *FeedAddPost_PostView_Reason) UnmarshalJSON(b []byte) error {
	typ, err := lexutil.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "net.nusno.gyoka.feed.addPost#skeletonReasonRepost":
		t.FeedAddPost_SkeletonReasonRepost = new(FeedAddPost_SkeletonReasonRepost)
		return json.Unmarshal(b, t.FeedAddPost_SkeletonReasonRepost)
	case "net.nusno.gyoka.feed.addPost#skeletonReasonPin":
		t.FeedAddPost_SkeletonReasonPin = new(FeedAddPost_SkeletonReasonPin)
		return json.Unmarshal(b, t.FeedAddPost_SkeletonReasonPin)
	default:
		return fmt.Errorf("closed unions must match a listed schema")
	}
}

// FeedAddPost_SkeletonReasonPin is a "skeletonReasonPin" in the net.nusno.gyoka.feed.addPost schema.
type FeedAddPost_SkeletonReasonPin struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.addPost#skeletonReasonPin"`
}

// FeedAddPost_SkeletonReasonRepost is a "skeletonReasonRepost" in the net.nusno.gyoka.feed.addPost schema.
type FeedAddPost_SkeletonReasonRepost struct {
	LexiconTypeID string `json:"$type" cborgen:"$type,const=net.nusno.gyoka.feed.addPost#skeletonReasonRepost"`
	// repost: AT-URI of the app.bsky.feed.repost record associated with this reason.
	Repost string `json:"repost" cborgen:"repost"`
}

// FeedAddPost calls the XRPC method "net.nusno.gyoka.feed.addPost".
func FeedAddPost(ctx context.Context, c lexutil.LexClient, input *FeedAddPost_Input) (*FeedAddPost_Output, error) {
	var out FeedAddPost_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.addPost", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
