// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.feed.trimFeedBefore

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// FeedTrimFeedBefore_Input is the input argument to a net.nusno.gyoka.feed.trimFeedBefore call.
type FeedTrimFeedBefore_Input struct {
	// before: Exclusive timestamp boundary. Posts indexed before this time are removed.
	Before string `json:"before" cborgen:"before"`
	// feed: AT-URI of the registered feed.
	Feed string `json:"feed" cborgen:"feed"`
}

// FeedTrimFeedBefore_Output is the output of a net.nusno.gyoka.feed.trimFeedBefore call.
type FeedTrimFeedBefore_Output struct {
	Before       string `json:"before" cborgen:"before"`
	DeletedCount int64  `json:"deletedCount" cborgen:"deletedCount"`
	Feed         string `json:"feed" cborgen:"feed"`
	Message      string `json:"message" cborgen:"message"`
}

// FeedTrimFeedBefore calls the XRPC method "net.nusno.gyoka.feed.trimFeedBefore".
func FeedTrimFeedBefore(ctx context.Context, c lexutil.LexClient, input *FeedTrimFeedBefore_Input) (*FeedTrimFeedBefore_Output, error) {
	var out FeedTrimFeedBefore_Output
	if err := c.LexDo(ctx, lexutil.Procedure, "application/json", "net.nusno.gyoka.feed.trimFeedBefore", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
