// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

// Lexicon schema: net.nusno.gyoka.ping

package gyoka

import (
	"context"

	lexutil "github.com/bluesky-social/indigo/lex/util"
)

// Ping_Output is the output of a net.nusno.gyoka.ping call.
type Ping_Output struct {
	Message string `json:"message" cborgen:"message"`
}

// Ping calls the XRPC method "net.nusno.gyoka.ping".
func Ping(ctx context.Context, c lexutil.LexClient) (*Ping_Output, error) {
	var out Ping_Output
	if err := c.LexDo(ctx, lexutil.Query, "", "net.nusno.gyoka.ping", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
